title: MaterialDigital Workflow Store
description: ""
theme: just-the-docs

baseurl: "/workflow-store"
url: "https://materialdigital.github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
