version: '3'
services:
  jekyll:
#    image: jekyll/jekyll:latest
    build: ./docs/
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./docs/:/srv/jekyll
    command: "bundle exec jekyll serve --host 0.0.0.0 --livereload"
