source 'https://rubygems.org'

gem "github-pages", group: :jekyll_plugins # compatibility to GitHub Pages - if used, no explicit jekyll gem needed
# gem "jekyll", "~> 4.3.2" # installed by `gem jekyll`
gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

# gem "just-the-docs", "0.7.0" # pinned to the current release
gem "just-the-docs"        # always download the latest release

